Repository Suryanataa/smkn4-web, pull requests merged in 2024-02, with the labels that each got.

#157 fix: level tenaga pendidik
  app/Http/Controllers/Dashboard/DashboardController.php
  app/Http/Controllers/Dashboard/SambutanKepsekController.php
  app/Http/Controllers/Dashboard/TenagaPendidikController.php
  app/Imports/PendidikImport.php
  database/migrations/2023_10_23_074355_create_tenaga_pendidik_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/TenagaPendidikSeeder.php
  resources/js/Components/Modal/FilterPegawai.jsx
  resources/views/auth/login.blade.php
  resources/views/dashboard/dashboard/partials/pendidik.blade.php
  resources/views/dashboard/pendidik/create.blade.php
  resources/views/dashboard/pendidik/edit.blade.php
  resources/views/dashboard/pendidik/export.blade.php
  resources/views/dashboard/pendidik/index.blade.php
  resources/views/layouts/footer.blade.php
Labels: bug

#158 theme website
  resources/js/Components/Card/CardSumPrestasi.jsx
  resources/js/Components/Card/MadingCard.jsx
  resources/js/Components/Card/MadingTitle.jsx
  resources/js/Components/Card/PostCard.jsx
  resources/js/Components/Card/PrestasiCard.jsx
  resources/js/Components/Copyright/Copyright.jsx
  resources/js/Components/Dropdown/DropLink.jsx
  resources/js/Components/Dropdown/Dropdown.jsx
  resources/js/Components/Dropdown/SideDropDown.jsx
  resources/js/Components/Footer/Footer.jsx
  resources/js/Components/Footer/Icons/IconLayout.jsx
  resources/js/Components/Navbar/Navbar.jsx
  resources/js/Components/Navbar/SubNavbar.jsx
  resources/js/Components/Sidebar/Sidebar.jsx
  resources/js/Layouts/CardListLayout.jsx
  resources/js/Layouts/FooterLayout.jsx
  resources/js/Layouts/LandingLayout.jsx
  resources/js/Layouts/MadingLayout.jsx
  resources/js/Pages/DetailJurusan.jsx
  resources/js/Pages/Home.jsx
  resources/js/Pages/Jurusan.jsx
  resources/js/Pages/Pegawai.jsx
  resources/js/Pages/Post.jsx
  resources/js/Pages/Prestasi.jsx
  resources/js/Pages/ProfilSekolah.jsx
Labels: enhancement

#160 theme finishing
  resources/css/app.css
  resources/js/Components/Button/ButtonFilter.jsx
  resources/js/Components/Button/ButtonPrimary.jsx
  resources/js/Components/Button/ButtonSecondary.jsx
  resources/js/Components/Card/CardSumPrestasi.jsx
  resources/js/Components/Card/JurusanCard.jsx
  resources/js/Components/Card/MadingCard.jsx
  resources/js/Components/Card/PegawaiCard.jsx
  resources/js/Components/Modal/FilterPegawai.jsx
  resources/js/Components/Modal/FilterPost.jsx
  resources/js/Components/Modal/FilterPrestasi.jsx
  resources/js/Components/Navbar/Navbar.jsx
  resources/js/Components/Pagination/Pagination.jsx
  resources/js/Layouts/CarouselCardLayout.jsx
  resources/js/Layouts/ModalLayout.jsx
  resources/js/Pages/DetailJurusan.jsx
  resources/js/Pages/Home.jsx
  resources/js/Pages/Jurusan.jsx
  resources/js/Pages/Pegawai.jsx
  resources/js/Pages/Post.jsx
  resources/js/Pages/Prestasi.jsx
  resources/views/app.blade.php
Labels: enhancement

#161 fix: status toggle
  app/Http/Controllers/Dashboard/PostController.php
  app/Http/Controllers/Dashboard/PrestasiController.php
  app/Http/Controllers/Dashboard/SubNavbarController.php
  resources/views/dashboard/post/index.blade.php
  resources/views/dashboard/prestasi/index.blade.php
  resources/views/dashboard/sub-navbar/index.blade.php
Labels: invalid

#162 refactor: toggle status
  app/Http/Controllers/Dashboard/PostController.php
  app/Http/Controllers/Dashboard/PrestasiController.php
  app/Http/Controllers/Dashboard/SubNavbarController.php
  resources/views/dashboard/post/index.blade.php
  resources/views/dashboard/prestasi/index.blade.php
  resources/views/dashboard/sub-navbar/index.blade.php
Labels: bug

#163 fix: toggle
  resources/views/dashboard/post/index.blade.php
  resources/views/dashboard/prestasi/index.blade.php
  resources/views/dashboard/sub-navbar/index.blade.php
Labels: bug

#164 fix:toggle
  resources/views/dashboard/post/index.blade.php
  resources/views/dashboard/prestasi/index.blade.php
  resources/views/dashboard/sub-navbar/index.blade.php
Labels: bug
